version: '3'
services:
  db:
    container_name: database
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3306:3306"

volumes:
  db_data:
